# Generated by Django 4.0.1 on 2022-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
