# Generated by Django 4.0.1 on 2022-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_alter_flight_departurecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
